spring:
  application:
    name: delivery-service

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: delivery-group-v2
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.user.delivery.model.InventoryUpdatedEvent

    listener:
      observation-enabled: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/delivery_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  reactor:
    context-propagation: auto

server:
  port: 8093

# Service URLs
order:
  service:
    url: http://nanokart-order-service:8083

user:
  service:
    url: http://nanokart-auth-service:8081

eureka:
  client:
    service-url:
      defaultZone: http://nanokart-eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

logging:
  pattern:
    correlation: '[${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]'