spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.user.login.inventory.event.PaymentCompletedEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    template:
      observation-enabled: true

    listener:
      observation-enabled: true

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

  reactor:
    context-propagation: auto

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.49
    instance-id: '${spring.application.name}:${server.port}'

management:
  endpoints:
    web:
      exposure:
        include: '*'

  tracing:
    enabled: true
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.web: INFO

  pattern:
    correlation: '[${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]'